### ISSUE TITLE
Jellfyfin Media Player playback broken due to libmpv API change

### ISSUE THREAD

**Issue by auxym** [Jonatas-Goncalves/MaxxedSUSE#10]
First of all, thanks for maintaining this repo :)

I noticed that jellyfin won't play music music anymore. Seems to be this issue (I get the exact same error in the log file): https://github.com/jellyfin/jellyfin-media-player/issues/579

Which seems to be caused by an API change in a recent libmpv update. The jellyfin team pushed a patch to fix it (linked in the issue).

Would it be possible to incorporate this patch in your build, in order to fix Jellyfin?

**Comment by Jonatas-Goncalves** [comment]
Thank you very much for the tip, I have already applied the patch Add Fix-MVP-Compatibility.patch to the package.
Media player playback now work normally.

Tested with jellifin-server on docker.
Please test it and let me know if it's working

**Comment by auxym** [comment]
It's working, thanks a lot for the quick fix!

**Comment by Jonatas-Goncalves** [comment]
You're welcome, as it's already working, I'll close this issue.

**Comment by Jonatas-Goncalves** [comment]
You're welcome, as it's already working, I'll close this issue.
