### ISSUE TITLE
Tweak for anbox-modules package.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#11]
Please tweak the .spec file to detect if there are other kernel versions installed (Tumbleweed updates always preserve 2 or more kernels before they get removed) or if the current system has `kernel-longterm` package installed, and update their respective module list (depmod).

With this tweak we ensure that the modules will be able to load in case the user installed the package with a more current version of the kernel but for some reason decided to boot with another previously installed version.

**Comment by Jonatas-Goncalves** [comment]
I added the parameters to update depmod for all kernel versions

Please test it and tell me if it worked.
