### ISSUE TITLE
Issue building anbox modules.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#12]
[https://build.opensuse.org/package/live_build_log/home:MaxxedSUSE/anbox-modules/openSUSE_Tumbleweed/x86_64](https://build.opensuse.org/package/live_build_log/home:MaxxedSUSE/anbox-modules/openSUSE_Tumbleweed/x86_64)

**Comment by JMarcosHP** [comment]
I think this don't work because KMP's are distributed for an specific kernel, they install on the respective directory but not in older kernels already installed, the point is to ensure the support for all kernels installed.

So we need to compile the same KMP for every kernel pushed to the main repo.

**Comment by JMarcosHP** [comment]
A quick and simply workaround for this is providing a dkms package to do the compiling/installing job on every kernel update.

**Comment by Jonatas-Goncalves** [comment]
I was having a compatibility problem between gcc and dkms from my dependency repository, it was giving an error when recompiling anbox-modules and other packages.

Make some modifications to use dkms in the package, please test it and let me know if it worked.

**Comment by Jonatas-Goncalves** [comment]
Closed because the problem has been resolved
