### ISSUE TITLE
Fix JamesDSP icon menu.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#14]
![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/7e1600af-8994-4f9e-9a9e-6f8959aa3450)

**Comment by Jonatas-Goncalves** [comment]
Fixed jasmesdsp.desktop parameters.
Fixed icon path in jamesdsp.desktop.

**Comment by Jonatas-Goncalves** [comment]
Closed because the problem has been resolved
