### ISSUE TITLE
Add patch fix for Waydroid container service and firewall.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#2]
Hello, the waydroid-container.service has issues with DBUS access.

Making some symlinks fixes the issue, so we can start the systemd unit and download the lineageOS images:

```
ln -s /usr/lib/waydroid/dbus/id.waydro.Container.conf /usr/share/dbus-1/system.d/
ln -s /usr/lib/waydroid/dbus/id.waydro.Container.policy /usr/share/polkit-1/actions/
ln -s /usr/lib/waydroid/dbus/id.waydro.Container.service /usr/share/dbus-1/services/
dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
```

firewall-cmd fix:

```
firewall-cmd --set-default-zone=trusted
firewall-cmd --zone=trusted --add-interface=waydroid0
firewall-cmd --reload
```

**Comment by Jonatas-Goncalves** [comment]
I restructured the Waydroid package, now it correctly installs the files: id.waydro.Container.conf, id.waydro.Container.policy, id.waydro.Container.service without the need for the above commands.
I added the requested fixes for Firewall and Dbus

I tested it here and it worked correctly.
I ask you to test it and let me know if it worked.

I ask that you pay attention to this when installing, because due to the synchronization time of the openSUSE Build Service repositories, which has been slow lately, the first package that I created before the modifications may still be included, please install the latest version of the package.

**Comment by JMarcosHP** [comment]
Thank you, I'm going to test on a TW fresh install to see if it works.

**Comment by Jonatas-Goncalves** [comment]
Forgot to mention:
Here I needed to use the psi=1 parameter when initializing the quenel to open the waydroid UI, it may not be necessary in a clean installation, test initially without, if you have problems apply the parameter and let me know.

If necessary, I will add this modification to the MaxxedSUSE script.

**Comment by JMarcosHP** [comment]
First of all, we need to add psi=1 to the bootloader kernel parameters (grub or systemd-boot).

There is something wrong with dkms/kmp rpm package. It successfull load the modules after installation but if you restart the host system, gbinder can't access /dev/anbox-binder.

I suggest you to drop the waydroid-image package because it causes some conflict/bootloop when you try to start via cli or gui.
So, the users can install/upgrade their preferred images (gapps/vanilla) manually on waydroid first launch.

Here are some debug output:

![Captura de pantalla 2024-03-19 015917](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/000e20a8-8de7-43c6-9876-30d72c65d8b3)

After system reboot gbinder can't access anbox modules but if you execute `# modprobe binder_linux` the system can load succesfully the modules, no mather what, gbinder can't access.

`$ waydroid session start`
![Captura de pantalla 2024-03-19 015951](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/cb4aba20-7faf-48c6-88d8-ee78babb1e72)

**Comment by Jonatas-Goncalves** [comment]
Rebuilt the package with some fixes:

I removed the recommendation for waydroid-image as requested
Fix path and permissions to dbus-1 and polkit-1 files
Add polkit-1 rules to initialize id.waydro.Container.policy

I tested it here and everything is working OK
Please test again and let me know if everything went well.

I ask you to check if the package has already been built at the link below, as it is in the repository's build queue as I made several changes today and it may take some time.
https://build.opensuse.org/package/show/home:MaxxedSUSE/waydroid

![Screenshot_20240321_063509](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/95e30ba6-f0fd-4aa3-a4ec-c4f8d6b99e2f)

**Comment by JMarcosHP** [comment]
anbox-kmp-default not working.

There are .ko files in /usr/lib/{kern}/updates, but can't probe that modules.

![Captura desde 2024-03-21 22-36-29](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/37349916-8ea0-462b-b0cd-d6daa4d7af78)

![Captura desde 2024-03-21 22-40-03](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/e01a75b1-f35c-45c2-8282-f5e97fb93a7c)

**Comment by Jonatas-Goncalves** [comment]
Please remove the package anbox-modules-dkms that you install in first print, is obsolete.
Only install anbox-modules.

**Comment by JMarcosHP** [comment]
When I installed the waydroid package I needed to specify the 1.4.2-4.1 version of the rpm package with the recent changes.

These are the anbox packages installed on my system:

![Captura desde 2024-03-21 23-02-12](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/6c481852-4b76-45b1-bbd4-b5971f01a838)

**Comment by Jonatas-Goncalves** [comment]
Here the modules are installing normally and running without problems, I will test a clean installation to try to identify what may be happening.
![Screenshot_20240322_021643](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/25a1706e-40b8-485e-aeae-1de119beb835)

**Comment by JMarcosHP** [comment]
My system has the new systemd-boot experimental feature and running the 6.8.1 kernel version. You are running 6.7.9.

I don't think kernel version or bootloader are the issue, because I tested with 6.7.9 and can't load the modules with the new packages. My system has secure-boot disabled.

**Comment by JMarcosHP** [comment]
Any fixes yet?

**Comment by Jonatas-Goncalves** [comment]
Sorry for the delay, I had to restructure the entire MaxxedSUSE repository due to the latest openSUSE updates and many libraries presented version incompatibility and other problems making these measures critical, I am separating the versions of Tumbleweed and Leap in the repository and removing Leap 15.5 and adding o 15.6.
That's why you also need to update the installation script here on github.

This week I will finish and resume the tests.

**Comment by Jonatas-Goncalves** [comment]
Sorry for the delay, I'm running a lot of tests at the same time.

Please retest waydroid and report if errors occur

**Comment by JMarcosHP** [comment]
> Sorry for the delay, I'm running a lot of tests at the same time.
> 
> Please retest waydroid and report if errors occur

Ok, I'm going to test on a real machine.

**Comment by JMarcosHP** [comment]
Add Python gbinder as dependency.

![Captura de pantalla_20240419_125548](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/32fe089d-3b40-425f-8d42-0d12f60dbb22)
![Captura de pantalla_20240419_125716](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/dd7001e1-f01b-483d-aea9-b21abece10fd)

**Comment by Jonatas-Goncalves** [comment]
It was an installation requirement before, I must have gone back to the previous spec version.

I already fixed it.


![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/0ca4cc04-0e62-4a84-8823-101260796b70)

**Comment by JMarcosHP** [comment]
Well done bro, It's fully working now even after reboot.

![Captura de pantalla_20240419_132830](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/02b239e7-787a-40ad-bf7f-7a1c385c95f1)
![Captura de pantalla_20240419_140254](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/4d8dcd56-a58d-46f5-bc3c-6b74d4da2601)
![Captura de pantalla_20240419_132714](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/7c05956c-30a0-440c-b02c-7acb4fa3c236)
![Captura de pantalla_20240419_140314](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/99229a75-2e96-4935-a5a6-721029692e5d)
![Captura de pantalla_20240419_140327](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/8706ce68-ac02-43fd-8bd2-a52c3773266d)
![Captura de pantalla_20240419_140643](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/edfed895-1175-4d1b-90c6-e7f83c91f151)
![Captura de pantalla_20240419_141943](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/c66fc37b-4f76-4753-8bee-279d6a91055a)

How do you managed to fix the anbox modules?

**Comment by Jonatas-Goncalves** [comment]
It didn't work, I created a new package using the repository you suggested in #3, making sure to send the files to the correct directories.

**Comment by Jonatas-Goncalves** [comment]
But I identified a problem in the apparmor parser for profiles.
Some files were not being created in the apparmor profile, I will send a correction now.

![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/dffc1242-a1b1-466b-879f-617d9ecd9804)

**Comment by JMarcosHP** [comment]
> But I identified a problem in the apparmor parser for profiles. Some files were not being created in the apparmor profile, I will send a correction now.
> 
> ![image](https://private-user-images.githubusercontent.com/34562990/324137757-dffc1242-a1b1-466b-879f-617d9ecd9804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NzAxNjgsIm5iZiI6MTcxMzU2OTg2OCwicGF0aCI6Ii8zNDU2Mjk5MC8zMjQxMzc3NTctZGZmYzEyNDItYTFiMS00NjZiLTg3OWYtNjE3ZDllY2Q5ODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIzMzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYWYwNTEzMGZjMjJjMzUzZTU4MzMyYTQ0ZGQwNjVlNjUxNGFlNjBlZmE0Yzc2Yjk5ZjE1ZDRkNjc0ZTk5YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.02nkmzy9sLSn6Z_chNRNtg1qhCr45XHuVia7l1E5npk)

Hi, I updated the package, 0 issues wth apparmor. Thanks

**Comment by JMarcosHP** [comment]
You can add waydroid to your script if you want. Or contact Waydroid developers to add the installation guide for Opensuse TW using your repository.

**Comment by JMarcosHP** [comment]
> You can add waydroid to your script if you want.

**Comment by Jonatas-Goncalves** [comment]
I've already added Waydroid to the script and many other new applications.
I will launch a new version of the script this week, with a more intuitive, selective and reusable menu.
I'm finalizing some errors in functions and trying to make it as simple as possible for beginner Linux users.

The news is big and interesting

For waydroid devs to use my package, my package needs to be accepted by the opensuse Factory team, and for that I need to be the official maintainer.
My priority now is to finish the Script, then I can send it to Factory and it will be available to everyone even outside my repository.

The process is more or less like the Yuzu package that I also sent to the factory before the Yuzu dropped.
https://build.opensuse.org/request/show/1128173?notification_id=45185102

Other packages I have already sent to Factory have been accepted and are available to everyone:
https://build.opensuse.org/package/show/X11:XOrg/optimus-manager
https://build.opensuse.org/package/show/X11:XOrg/nvidia-prime
https://build.opensuse.org/package/show/X11:XOrg/EnvyControl
https://build.opensuse.org/request/show/1094377?notification_id=41364647

**Comment by JMarcosHP** [comment]
Thank you a lot for your hard work, If you need help, you can contact me for testing. Another package I wish you to add is [JamesDSP for Linux](https://github.com/Audio4Linux/JDSP4Linux).

**Comment by Jonatas-Goncalves** [comment]
That's a pleasure!
Please test if package waydroid-magisk is working correctly.


About JamesDSP:
open a new issue and I'll put the package in my repository and script.
