### ISSUE TITLE
Request for kmp or dkms package binder ashmem modules.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#3]
There is a fork of anbox modules with fixes for kernel 6.7 and 6.8. I compiled these modules and now waydroid is fully working on openSUSE Tumbleweed (kern 6.7).

You can make the respective package and add dependency for waydroid, so the community can have waydroid fully working on openSUSE.

Link:
[anbox-modules](https://github.com/choff/anbox-modules)

**Comment by JMarcosHP** [comment]
![Captura desde 2024-03-15 14-39-03](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/ae9662df-667e-4cb5-9b59-6cf3ca3b1491)
![Captura desde 2024-03-15 14-40-43](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/ca4fb062-c335-4518-af77-80adc30cc40b)

**Comment by Jonatas-Goncalves** [comment]
I created the anbox-modules package from the informed repository and placed the package as a dependency on the waydroid package.

Thanks for this tip.

**Comment by Jonatas-Goncalves** [comment]
I created the anbox-modules package from the informed repository and placed the package as a dependency on the waydroid package.

Thanks for this tip.
