### ISSUE TITLE
Anbox modules not working again (Kernel 6.8.7)

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#4]
![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/df068951-9c11-4066-a60b-439a514710cc)

**Comment by JMarcosHP** [comment]
On Kernel 6.8.6 is working.
![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/b6d4f257-3d38-47f0-a3ea-3003acf6e41c)

**Comment by JMarcosHP** [comment]
Aparently, the kernel modules are in /usr/lib/modules/{kern}/updates on both kernels.
But something is wrong with 6.8.7 that causes the modules can't get recognized. Maybe a missing symlink?

**Comment by JMarcosHP** [comment]
Kernel 6.8.6 has anbox-binder symlink and binder,ashmem,hwbinder files in /dev:

![Captura de pantalla_20240423_133355](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/c89207a0-3c8a-4cbf-928a-f9e39effa7d9)

Kernel 6.8.7 don't has the files, the modules are not loading correctly or not creating the respective files in /dev
![Captura de pantalla_20240423_133551](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/3eeffc5b-36a4-4566-a928-1bdf8abc41be)

**Comment by JMarcosHP** [comment]
Executing `sudo depmod -a` I can succesfully load the modules on Kernel 6.8.7 but needs to reboot to execute waydroid correctly. You should add that command on rpm .spec after every package update or kernel update and add the `needs-restarting`  flag.

**Comment by JMarcosHP** [comment]
Or you can build a single KMP package including the module source using `%kernel_module_package` to handle this automatically and add a notification to restart de system.

Here are some docs from [SUSE](https://documentation.suse.com/sbp/server-linux/html/SBP-KMP-Manual-SLE12SP2/index.html)

**Comment by Jonatas-Goncalves** [comment]
The package has been updated to run depmod after install/uninstall and include restart notification.
Modules are loading after reboot.

![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/e0670e03-f559-4131-b6fa-f00bb3ae6e00)

**Comment by JMarcosHP** [comment]
Thank you, now Waydroid is fully working.
